apiVersion: apps/v1
kind: Deployment
metadata:
  name: cats-dogs-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cats-dogs
  template:
    metadata:
      labels:
        app: cats-dogs
    spec:
      containers:
      - name: cats-dogs-container
        image: cats-dogs-mlops:local
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10